- hosts: localhost
  gather_facts: false
  connection: local
  tasks:
  # get date
  - set_fact: creationdate="{{lookup('pipe','date "+%Y/%m/%d %H:%M"')}}"
  - name: Create a VM from a template
    vmware_guest:
      hostname: 10.10.10.15
      username: administrator@paosin.local
      password: P@ssw0rd
      validate_certs: no
      folder: /Centos7
      name: Centos7
      state: poweredon
      template: Centos7
      disk:
      - size_gb: 10
        type: thin
        datastore: hdd2TB
      hardware:
        memory_mb: 512
      networks:
      - name: VM Network
        mac: aa:bb:dd:aa:00:14
      wait_for_ip_address: yes
    delegate_to: localhost
    register: deploy
